### ISSUE TITLE
add boostrap4 preset

### ISSUE THREAD

**Issue by Bonobomagno** [laravel-frontend-presets/internals#3]
hello guys, 
what about a boots4 preset?

**Comment by OwenMelbz** [comment]
I don't think there are any "Planned" releases - this was merely a community centralised group of repositories. So if people have released a preset - we can add it here for people to find easily.

Rather than creating and supporting a range of presets.

So to answer your question - sure somebody can make a bootstrap preset and we'll add it.

But no there's not like an official road plan or anything

**Comment by m1guelpf** [comment]
@Bonobomagno You're free to create one, and we'll add it to the organization and give you admin access to your repository. :smile:

**Comment by m1guelpf** [comment]
@Bonobomagno You have the contributing instrucions and detailed information on how to add a preset at [our website](https://laravel-frontend-presets.github.io).

**Comment by ovvessem** [comment]
Bootstrap4 Preset has just became available - https://github.com/laravelnews/laravel-twbs4

**Comment by OwenMelbz** [comment]
@ovvessem they’ve told us they want to keep separate - so won’t be covered unless somebody else submits one
